package internal

const (
	OPENV_KEYS                            = "OPENV_KEYS"
	OPENV_KEYS_ORG_VARIABLES              = "OPENV_KEYS_ORG_VARIABLES"
	OPENV_KEYS_ORG_SECRETS                = "OPENV_KEYS_ORG_SECRETS"
	OPENV_KEYS_REPO_VARIABLES             = "OPENV_KEYS_REPO_VARIABLES"
	OPENV_KEYS_REPO_SECRETS               = "OPENV_KEYS_REPO_SECRET"
	OPENV_KEYS_REPO_ENVIRONMENT_VARIABLES = "OPENV_KEYS_REPO_ENVIRONMENT_VARIABLES"
	OPENV_KEYS_REPO_ENVIRONMENT_SECRETS   = "OPENV_KEYS_REPO_ENVIRONMENT_SECRETS"
)

var (
	OPENV_KEYS_LIST = []string{
		OPENV_KEYS,
		OPENV_KEYS_ORG_VARIABLES,
		OPENV_KEYS_ORG_SECRETS,
		OPENV_KEYS_REPO_VARIABLES,
		OPENV_KEYS_REPO_SECRETS,
		OPENV_KEYS_REPO_ENVIRONMENT_VARIABLES,
		OPENV_KEYS_REPO_ENVIRONMENT_SECRETS,
	}
)
